name = "worker"
type = "javascript"
account_id = "c60e829b3831ea5b11b2398ef68bda23"
workers_dev = true
route = ""
zone_id = "92b49b326b3b0fa80b5c478ce242e93e"

[build]
command = "npm install && npm run build"
[build.upload]
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [{name = "COUNTER", class_name = "Counter"}]
