name = "miamipool"
type = "javascript"
zone_id = ""
account_id = "c60e829b3831ea5b11b2398ef68bda23"
route = ""
workers_dev = true

[build]
command = "yarn && yarn format && yarn build"
[build.upload]
format = "service-worker"
main = "worker.js"

[triggers]
crons = ["* * * * *"]