[project]
name = "miamipool"
requirements = []

[contracts.miamipool]
path = "contracts/miamipool.clar"
depends_on = []

[contracts.citycoin-vrf]
path = "contracts/citycoin-vrf.clar"
depends_on = []

[contracts.citycoin-core-trait]
path = "contracts/citycoin-core-trait.clar"
depends_on = []

[contracts.citycoin-token-trait]
path = "contracts/citycoin-token-trait.clar"
depends_on = []

[contracts.citycoin-auth]
path = "contracts/citycoin-auth.clar"
depends_on = ["citycoin-core-trait", "citycoin-token-trait"]

[contracts.citycoin-token]
path = "contracts/citycoin-token.clar"
depends_on = ["sip-010-trait", "citycoin-auth", "citycoin-token-trait"]

[contracts.citycoin-core-v1]
path = "contracts/citycoin-core-v1.clar"
depends_on = ["citycoin-auth", "citycoin-token", "citycoin-vrf", "citycoin-core-trait"]

# contracts listed below are used only in testing

[contracts.sip-010-trait]
path = "contracts/sip-10-ft-standard.clar"
depends_on = []