name = "ui"
type = "webpack"
# account_id = "c60e829b3831ea5b11b2398ef68bda23"
# set this as CF_ACCOUNT_ID in a .env file in here, otherwise it won't work.
# this is for syvita's account which you can't access
workers_dev = true
route = ""
zone_id = ""
webpack_config = "node_modules/flareact/webpack"

# kv_namespaces = [
#   { binding = "Zion", id = "1b7a1ecc8323448d9039addeaa990bce", preview_id = "34dbcb92daf945aeb5e6d88e6c87789c" }
# ]

[site]
bucket = "out"
entry-point = "./"
