name: Contracts
on: push

jobs:
  clarinet:
    runs-on: ubuntu-latest
    container:
      image: hirosystems/clarinet
    steps: 
      - name: checkout code
        uses: actions/checkout@v2
      - name: check contract syntax
        working-directory: ./packages/onchain
        run: clarinet check
      - name: run tests
        working-directory: ./packages/onchain
        run: clarinet test